### PR TITLE
Enhance flow configuration and remove lodash

### PR DESCRIPTION
**Pull request by pbomb**
I would like to import the `EffectFunction` flow type in our product, so I've added that in addition to a .flowconfig file so we can run flow against the project.

I also removed lodash in a second commit. Since this library is so small the the usage of lodash is just for iterating over arrays, I removed it in favor of standard ES5 usages of `forEach` and `reduce`.

### CODE REVIEW

**Comment by brentvatne** [comment]
Looks great to me, thanks!

**Comment by brentvatne** [comment]
Also, I made you a collaborator on this repo :>

**Comment by brentvatne** [comment]
Published in 1.0.2

**Comment by pbomb** [comment]
:+1: thanks!

**Pull request merged**
